version: '3.7'

services:

  einhundert_app:
    container_name: einhundert_app
    build:
      dockerfile: deploy/django.Dockerfile
    image: einhundert_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app