# Generated by Django 4.2.11 on 2024-04-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonIntensityTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('intensity_forecast', models.IntegerField()),
                ('intensity_actual', models.IntegerField()),
                ('intensity_index', models.CharField(max_length=10)),
            ],
        ),
    ]
